### PR TITLE
Add DEA Sandbox disclaimer to documentation. Disclaimer approved as o…

### PR DESCRIPTION
**Pull request by CEKrause**
Add in approved DEA Sandbox disclaimer to documentation.

### CODE REVIEW

**Comment by CEKrause** [comment]
Note that some new words are being added to the DEA Sandbox landing page that will direct users to this new page.

**Comment by robbibt** [comment]
This looks great @CEKrause! One suggestion: is there any chance we could move the disclaimer inside the "DEA Sandbox" heading here?
image

The list of headings under Access is already getting pretty long, and it'd be good to keep it as simple as we can (non-Sandbox users probably don't need to see the disclaimer unless they click into that section)

**Comment by CEKrause** [comment]
We can, if that's the consensus? My thought behind having it at that level is that it's important for people to be able to find it without digging too far. But it's going to be directly hyperlinked from the Sandbox landing page, so maybe it doesn't matter. 
I can move it down a level if you'd prefer.

**Comment by robbibt** [comment]
This is how DE Africa has theirs set up - I think this example a bit _too_ hidden two levels down, but one level might be a good balance to keep all Sandbox material together while keeping the front page as clean as possible:

https://docs.digitalearthafrica.org/en/latest/sandbox/termsconditions.html

**Comment by CEKrause** [comment]
@robbibt thanks for the suggestion. I have moved the content and gotten rid of the new page. As far as I can tell it should all be good now, but it's hard to tell until the page is built whether all the syntax has worked.

**Comment by omad** [comment]
That looks good to me Claire. There's a formatting issue with the first section, **bold** `**` markers need to be on a single line.

And I agree with Robbi, it would be better to be under **DEA Sandbox** rather than it's own table of contents entry.

**Review by robbibt — APPROVED** [review]
Looks great to me!

**Pull request merged**
