### PR TITLE
New mock imports file

### PR DESCRIPTION
**Pull request by benji-glitsos-ga**
We need to add all Python dependencies to a list of mock imports on the KH, as was found in this bug fix: https://github.com/GeoscienceAustralia/dea-docs/pull/123

To make this more discoverable, I've moved the mock imports into a different file: `/docs/mock_imports.txt`

I'll then document this mock_imports.txt file.

Also, I moved the `requirements.txt` file into the docs folder so it sits next to the mock imports file.

### CODE REVIEW

**Comment by robbibt** [comment]
Hey @benji-glitsos-ga , it looks like this is correctly getting all the new content now. 👍

Is the mock required given we have now updated DEA Tools to add `rioxarray` to the requirements/setup.py? Or do we need to replicate all requirements here too to get the docs to work?

**Comment by benji-glitsos-ga** [comment]
> Hey @benji-glitsos-ga , it looks like this is correctly getting all the new content now. 👍
> 
> Is the mock required given we have now updated DEA Tools to add `rioxarray` to the requirements/setup.py? Or do we need to replicate all requirements here too to get the docs to work?

Hi Robbi, yep it turns out that the requirements are needed here as well. So it means we must add each requirement to two places - the dea-notebooks and dea-docs.

**Comment by benji-glitsos-ga** [comment]
@robbibt This is now ready for your review. The significant parts of this PR are:

* https://github.com/GeoscienceAustralia/dea-docs/pull/122/files#diff-2db264c3dccd2d75f0361d73e7705f6ca8cb2c68724e30880104804294ef2dcc
* https://github.com/GeoscienceAustralia/dea-docs/pull/122/files#diff-11d8a7b639300b2bd0704ccbe28946e4ab307f8185028df537f9962b558b4d09

**Comment by benji-glitsos-ga** [comment]
@robbibt To answer your questions:

1. We'll know for sure if next time nothing breaks :)
2. The list was originally in a python file inside the /docs/ _modules subfolder. I thought it would be easier to find the file if I put it in the /docs/ folder so it sits next to the requirements.txt file.

**Comment by robbibt** [comment]
> @robbibt To answer your questions:
> 
> 1. We'll know for sure if next time nothing breaks :)
> 2. The list was originally in a python file inside the /docs/ _modules subfolder. I thought it would be easier to find the file if I put it in the /docs/ folder so it sits next to the requirements.txt file. I actually didn't consider that it could just be a python file instead of a txt file. Do you think it should be Python?

It was originally defined in Python here in `docs/_modules/mock_imports.py`, was just wondering why the change. All good though, will accept the PR 🙂 

image

**Review by robbibt — APPROVED** [review]

**Pull request merged**
