### PR TITLE
Add STAC doco

### PR DESCRIPTION
**Pull request by jmettes**
Added some information about accessing data using odc-stac. Reorganised the WMS/WCS stuff so it made more sense.

image

### CODE REVIEW

**Comment by jmettes** [comment]
[DE Africa](https://docs.digitalearthafrica.org/en/latest/sandbox/notebooks/Frequently_used_code/Downloading_data_with_STAC.html) has some more doco on using STAC without odc-stac, which might be worth including.

There also seems to be a [QGIS plugin for STAC](https://stac-utils.github.io/qgis-stac-plugin/), which might be worth experimenting with and including.

**Review by CEKrause — APPROVED** [review]
The changes look good to me (from a content point of view). I love that we have WCS documented now! There was a customer query just this morning that I can now point to this documentation to answer.

**Comment by robbibt** [comment]
This looks fantastic! Two quick comments:

- Can we spell out the acronym in the title to match the other listings? "Spatiotemporal Asset Catalogue (STAC)" 
- We do already have a STAC notebook in the User Guide, but it doesn't use `odc-stac` and is focused more on loading external data directly into the existing DEA environment (rather than loading DEA data into an external environment). In the future we can think about merging both of these - for now we perhaps might want to add a link at the bottom pointing to the existing notebook for people who want more info

**Comment by jmettes** [comment]
@robbibt Yep, I agree. For now, I can link to the other non-`odc-stac` STAC page. I had thoughts about either:
1) re-writing that page to be `odc-stac` only
2) adding an 'exploration' section under the new page I added, to cover the workings of the API and metadata, etc.

Is `odc-stac` our recommended way for our users to interact with our STAC endpoint? Because that would be the perception, as the way the page is currently laid out now.

@CEKrause This is my first attempt at creating a section more focused on external access. I'll revisit this doco again once https://github.com/opendatacube/datacube-ows/issues/798 has been released - I'll update the WCS doco on programmatic access.

**Comment by robbibt** [comment]
> @jmettes Is `odc-stac` our recommended way for our users to interact with our STAC endpoint? Because that would be the perception, as the way the page is currently laid out now.

That's an excellent question, and probably one for the DEA slack channel (or at least getting some other opinions in this thread). My feeling is probably "yes", assuming that `odc-stac` is definitely something that will see ongoing development? The code in this example is nice and simple which is good for a recommended method for accessing the data. The other notebook was written before `odc-stac` was a thing which explains some of the different methods used there - that said, some things like plotting up STAC results using `geopandas` is definitely very useful functionality that we will want to keep going forward regardless of how the data is loaded.

Two other quick thoughts that occurred to me since yesterday:

- Should we add in `!pip install pystac-client` and `!pip install odc-stac` up the top of this guide to make it fully reproducible?
- We should change `resolution = 25` to `resolution = 30` to reflect the new resolution of our Landsat Collection 3 data

**Comment by jmettes** [comment]
Thanks for all the feedback @robbibt! I've added your suggestions.

**Review by robbibt — APPROVED** [review]
Thanks @jmettes, looks great!

**Pull request merged**
