### PR TITLE
Tags feature

### PR DESCRIPTION
**Pull request by benji-glitsos-ga**
ksnip_20240202-141900

This feature includes the following.

* Each product page has a list of tags.
* Each tag has its own page that lists all pages that are tagged by the tag.
* There is an index page that lists all tags on the site.

Note that the preview site isn't reliable for demoing this feature since it uses an older version of Python (3.8 instead of 3.11). Also, I cannot test reliably on my local computer due to a caching issue. Therefore, the best way to test this may be to publish it live then roll back if needed.

### CODE REVIEW

**Comment by robbibt** [comment]
Hey @benji-glitsos-ga, this looks great. When you have time, we should have a think about how tags will work with DEA Notebooks going forward - our current tagging system there is far too messy at the moment, but in the future it would be valuable to have that content nicely tagged too and integrated with Knowledge Hub tagging (to increase visibility of the various tools and notebooks we have there).

**Comment by benji-glitsos-ga** [comment]
@robbibt Definitely - it will be great if we start tagging the Notebooks (and User Guides). There are a few things we will need to consider such as: will it display visual clutter on the sandbox, and will the product tags overlap too much with the notebook tags and become messy.

**Comment by robbibt** [comment]
We do already have tags - you can see them at the bottom of the notebooks here:
https://docs.dea.ga.gov.au/notebooks/DEA_products/DEA_Fractional_Cover.html#Tags

But they don't use a controlled vocabulary, so they're messy and inconsistent.

I think we'd probably need to re-do them from scratch, making sure we use a small and useful set of controlled terms that play nicely with the existing product tags (but things like using the same product tags in both the product guides and product notebooks would actually be really useful).

**Comment by benji-glitsos-ga** [comment]
Note to Claire:
This feature can't be tested accurately on the demo sites because they use a slightly older version of Python unfortunately. That is a limitation of using Netlify
Also, I have trouble testing on my local environment due to a caching issue.
Therefore, the best way to test would be to deploy it live then quickly roll back if it doesnt work.
The main issue that may happen is that the tag pages don't get generated. This won't break the site at all.

**Review by CEKrause — APPROVED** [review]
Approved pending testing in prod. Thanks @benji-glitsos-ga

**Pull request merged**
